### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by sirBobz** [ppokrovsky/pyvdp#1]
I cloned your repo to my computer. I navigated to /pyvdp/demo then run **python manage.py runserver**

This was the response on the terminal:
Validating models...

0 errors found
February 23, 2017 - 11:06:43
Django version 1.6.11, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[23/Feb/2017 11:07:18] "GET / HTTP/1.1" 500 98256

However, on the browser the importError was displayed;

**ImportError at /**

No module named **visadirect.fundstransfer**

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/
Django Version: 	1.6.11
Exception Type: 	ImportError
Exception Value: 	

No module named **visadirect.fundstransfer**

Exception Location: 	/var/www/html/pyvdp/demo/demo/views.py in <module>, line 3
Python Executable: 	/usr/bin/python
 

Please address this.

**Comment by ppokrovsky** [comment]
What OS and Python version are you using?

What is the value of PYTHONPATH env variable?

**Comment by ppokrovsky** [comment]
Please comment if you managed to sort it out on your own.

**Comment by sirBobz** [comment]
Hi there, 

I have not tested once more. Let me do it in a few hours. I will get back if need be. 

Seen you made a couple of changes. 

Regards
